export type StatusType = 'Active' | 'Pending' | 'Suspended';

export type User = {
  initials: string;
  color: string;
  name: string;
  role: 'Student' | 'Lecturer' | 'Admin';
  dept: string;
  status: StatusType;
  email: string;
  phone: string;
  joined: string;
  courses: string;
  sessions: string;
};
export const USERS: User[] = [
  {
    initials: 'DM',
    color: '#1c3f7a',
    name: 'Dr. Makane',
    role: 'Lecturer',
    dept: 'Computer Science',
    status: 'Active',
    email: 'makane@edustream.edu',
    phone: '+237 677 234 112',
    joined: 'Jan 12, 2023',
    courses: '4 courses',
    sessions: '142 sessions',
  },
  {
    initials: 'DF',
    color: '#0e7490',
    name: 'Dr. Fortunee',
    role: 'Lecturer',
    dept: 'Engineering',
    status: 'Active',
    email: 'fortunee@edustream.edu',
    phone: '+237 699 881 034',
    joined: 'Mar 08, 2022',
    courses: '5 courses',
    sessions: '178 sessions',
  },
  {
    initials: 'CA',
    color: '#166534',
    name: 'Carl Asonganyi',
    role: 'Admin',
    dept: 'Registry',
    status: 'Active',
    email: 'carl@admin.edu',
    phone: '+237 677 900 001',
    joined: 'Feb 15, 2021',
    courses: 'N/A',
    sessions: '310 sessions',
  },
  {
    initials: 'PR',
    color: '#7c3aed',
    name: 'Precious Ndi',
    role: 'Admin',
    dept: 'IT Services',
    status: 'Active',
    email: 'precious@admin.edu',
    phone: '+237 699 900 002',
    joined: 'Jun 01, 2020',
    courses: 'N/A',
    sessions: '287 sessions',
  },
  {
    initials: 'CH',
    color: '#4338ca',
    name: 'Che Fontem',
    role: 'Admin',
    dept: 'Examinations',
    status: 'Active',
    email: 'che@admin.edu',
    phone: '+237 677 900 003',
    joined: 'Sep 10, 2022',
    courses: 'N/A',
    sessions: '195 sessions',
  },
  {
    initials: 'S1',
    color: '#854d0e',
    name: 'Student One',
    role: 'Student',
    dept: 'Engineering',
    status: 'Active',
    email: 'student1@student.edu',
    phone: '+237 677 100 001',
    joined: 'Sep 03, 2024',
    courses: '6 enrolled',
    sessions: '89 sessions',
  },
  {
    initials: 'S2',
    color: '#991b1b',
    name: 'Student Two',
    role: 'Student',
    dept: 'Medicine',
    status: 'Pending',
    email: 'student2@student.edu',
    phone: '+237 677 100 002',
    joined: 'Nov 28, 2024',
    courses: '3 enrolled',
    sessions: '12 sessions',
  },
  {
    initials: 'S3',
    color: '#065f46',
    name: 'Student Three',
    role: 'Student',
    dept: 'Law',
    status: 'Suspended',
    email: 'student3@student.edu',
    phone: '+237 677 100 003',
    joined: 'Sep 03, 2023',
    courses: '5 enrolled',
    sessions: '0 sessions',
  },
  {
    initials: 'S4',
    color: '#1e40af',
    name: 'Student Four',
    role: 'Student',
    dept: 'Sciences',
    status: 'Active',
    email: 'student4@student.edu',
    phone: '+237 677 100 004',
    joined: 'Sep 03, 2024',
    courses: '5 enrolled',
    sessions: '67 sessions',
  },
  {
    initials: 'S5',
    color: '#6b21a8',
    name: 'Student Five',
    role: 'Student',
    dept: 'Arts & Social Sci.',
    status: 'Active',
    email: 'student5@student.edu',
    phone: '+237 677 100 005',
    joined: 'Sep 03, 2024',
    courses: '4 enrolled',
    sessions: '54 sessions',
  },
];
